### ISSUE TITLE
fieldservice_helpdesk_stock 11.0.0.0.1

### ISSUE THREAD

**Issue by max3903** [ursais/osi-addons#12]
License: LGPL-3
Dependencies: fieldservice_stock, helpdesk_stock
Auto Install: True

# Module Description

Odoo Field Service App allows to manage service requests and orders. The app does not support the logistic side of those activities: Sometimes, the dispatcher need to ship materials to the field service person or to the serviced location.

Odoo Helpdesk App allows to manage support tickets or customer service requests. The app does not support the logistic side of those activities: Sometimes, helpdesk users need to ship materials to the customer or to the serviced location to solve a ticket.

This module allows to integrate material request between a helpdesk ticket and field service order to be shipped to the customer location or serviced location and follow up with the Inventory team.

# Usage
* Create a service order with a customer and a ticket
* In Inventory, add products with quantity
* Click on Confirm
  * The delivery order is created
  * The transfer is set on the ticket
  * The state is updated to Confirmed
  * The product, description and quantity requested cannot be changed
* Transfer partially the delivery order
  * The state is updated to Partially Shipped
* Transfer completely the delivery order
  * The state is updated to Done

# Technical Specifications
## Field Service Order Line
* Add a many2one field "Helpdesk Ticket Line" (helpdesk_ticket_line_id) to helpdesk.ticket.line

## Helpdesk Ticket Line
* Add a many2one field "Field Service Order Line" (fsm_order_line_id) to fsm.order.line

## Field Service Order
* When a fsm.order.line is created, if the service order is linked to a ticket, a helpdesk.ticket.line is created with the same information and linked to the field service order line
* When a fsm.order.line is confirmed, the related helpdesk.ticket.line is confirmed and linked to the same delivery order.
* When a helpdesk.ticket.line is confirmed, if the "Field Service Order Line" is set, then the field service order line is also confirmed and linked to the same delivery order.

**Comment by bodedra** [comment]
@max3903 I am working on these. I can not find `fsm.order.line` object. Do I miss anything?

**Comment by max3903** [comment]
@bodedra Update field-service:
https://github.com/OCA/field-service/blob/11.0/fieldservice_stock/models/fsm_order.py#L71
