### ISSUE TITLE
[ADD] agreement_sale_subscription_suspension

### ISSUE THREAD

**Issue by max3903** [ursais/osi-addons#120]
Dependencies: agreement_serviceprofile, agreement_sale_subscription +
- [x] #118 

This module will suspend all the services of an agreement if the related subscription is suspended.

# Usage

* Create a subscription product and check the box "Create a Service Profile" on the "Agreement" tab
* Create a sale order with an agreement template and the previous product
* Confirm the sale order. The subscription, agreement and service profile get created and linked together.
* On the subscription, click on "Suspend". The service profile is suspended.
* On the subscription, click on "Re-Activate". The service profile is re-activated.

# Technical Specifications

## sale.subscription

- [x] When a subscription is suspended, move all the service profiles of the related agreement in the "Suspended" state
- [x] When a subscription is re-activated, move all the service profiles of the related agreement in the "In Progress" state

**Comment by max3903** [comment]
@barnarj I can't find the pull request for this issue. Can you help me?

**Comment by barnarj** [comment]
@max3903 It appears this was in #180
