### ISSUE TITLE
agreement_sale_subscription

### ISSUE THREAD

**Issue by max3903** [ursais/osi-addons#19]
Dependencies: 
* agreement_sale: https://github.com/OCA/contract/issues/234
* sale_subscription

License: LGPL-3

# Module description
Odoo Sales Subscription App does not support the management of legal content for agreement and contract. It's also not integrated with the Agreement App. The Agreement App does not support recurring invoicing with all the reporting and accounting that comes with subscriptions and deferred revenues.

This module will allow you to perform recurring invoicing of subscription products and review their performance from the agreement.

# Configuration
* Create a subscription template
* Create an agreement template
* Set the agreement sections on the subscription product

# Usage
* Go to Sales
* Create a quotation, set the agreement template and add a subscription product
* Confirm the quotation --> The agreement is linked to the created subscription and vice versa.

# Technical Specifications
- [x] Add a readonly many2one field "Subscription" (subscription_id) on the agreement to sale.subscription
- [x] Add a readonly many2one field "Agreement" (agreement_id) on the subscription to agreement
- [x] When the sales order is confirmed and the subscription created, the subscription is linked to the agreement and vice versa.

**Comment by brian10048** [comment]
@max3903 Thanks for pointing me over to this repository! I look forward to a subscription and field service link.  If you need me to help with this or the OCA dependency for it, just let me know.
