### ISSUE TITLE
[IMP] helpdesk_fieldservice

### ISSUE THREAD

**Issue by brian10048** [ursais/osi-addons#249]
@max3903 

Curious if I could submit a PR to remove the validation logic that checks for an end date and resolution before the call to super in the action_complete method of fsm_order.py in the helpdesk_fieldservice module

1. This same validation logic is already in fieldservice_isp_flow.  
2. I call a wizard with the action_complete method which then sets the end date and resolution notes, so this validation would break the flow in my use case.

If you guys need to keep it, I will just modify my own locally.

**Comment by max3903** [comment]
@brian10048 I think we could have a module to select a list of fields on a stage and when the stage of an FSM is changed, check that each of the fields in the list of the target stage are set.

**Comment by brian10048** [comment]
I like that idea and think I could put it together.

On fsm.stage add a many2many to ir.model.fields filtered only to include fields of fsm.order

Add a method to fsm.order that depends on stage_id
Raise validation error if any of the many2many fields are not set for the new stage

Any other thoughts?  Put in OCA or would you prefer it in this repo?

**Comment by max3903** [comment]
:+1: 

You can also do it from the `write` method or with `api.constrains`. Up to you.

In the OCA.

**Comment by brian10048** [comment]
Sounds good, thanks for the feedback
