### ISSUE TITLE
O v12 when trying to install the osi-addons

### ISSUE THREAD

**Issue by marcos-mendez** [ursais/osi-addons#274]
You try to install module 'helpdesk_stock' that depends on module 'helpdesk_timesheet'.
But the latter module is not available in your system. 

After searching for this module the only one i found was for v11 https://github.com/agenterp/helpdesk/tree/11.0_helpdesk_helpdesk_timesheet

How can this be installed for testing?

**Comment by bodedra** [comment]
'helpdesk_timesheet' is a enterprise module and 'helpdesk_stock' is not a compatible with community edition.

If you face any issue or bug, feel free to report it.

**Comment by marcos-mendez** [comment]
But how is possible that an OCA module depends on a Enterprise module?

Also if it is GPL so Enterprise will become gpl?

I dont understand sorry
