### ISSUE TITLE
Pre-Commit Failed Due to Python Version

### ISSUE THREAD

**Issue by Hardik-OSI** [ursais/osi-addons#407]
https://github.com/ursais/osi-addons/blob/3defe644f5f4f451aea7be789874bf29b5634dd4/.github/workflows/pre-commit.yml#L13

As mentioned in Issue :- https://github.com/OCA/oca-addons-repo-template/issues/80
We Also face this issue due to by default it takes python:3.10 
This Issue solved in this reference :- https://github.com/OCA/oca-addons-repo-template/blob/master/src/.github/workflows/pre-commit.yml#L8

Can we Change this or there is any other way? @max3903 
Thanks.

**Comment by max3903** [comment]
Fixed.
