### ISSUE TITLE
MRP inventory valuation for serial product get wrong

### ISSUE THREAD

**Issue by Murtaza-OSI** [ursais/osi-addons#455]
Description:-
1)Product with serial tracking, Force Removal Strategy: -FIFO ,Costing Method:-FIFO.
Have issue of if we having the product as followed.
![1](https://user-images.githubusercontent.com/77261450/172121252-69643b8f-cb8a-4b8d-92f0-e7c3dd492785.png)
2) Create MO with Following Component.
Check the Cost for Finnish Product.
![2](https://user-images.githubusercontent.com/77261450/172121465-804a7545-62e7-4f4e-b2eb-c527f3d26baa.png)
![3](https://user-images.githubusercontent.com/77261450/172121509-a058678e-ce5d-45d9-9edd-3c96c3384a63.png)
 As we can see the issue here is component with Sr.no:- 4563  Cost is $50. But is calculated the cost of finish good base of FIFO.
 3) If we created MO with Component cost $100 it will take $50 cost price as per the FIFO.
 ![4](https://user-images.githubusercontent.com/77261450/172122156-99a0ba44-0b91-43b3-85b3-5e568e1fbc87.png)
![5](https://user-images.githubusercontent.com/77261450/172122176-b4ca04b5-7b60-48aa-aad8-91f12bed0dca.png)
##################################################################################################

**Solution:-**

We have module osi_fifo_serialized_fix in which this issue is fix for Sale Order Delivery Order.
Enhances the module for  MRP Inventory Valuation
Following Output after enhancement:-
1) PO the product with 3 different rate
![6](https://user-images.githubusercontent.com/77261450/172122944-d034ec7e-4f5a-4e23-b084-f12540917d4d.png)
2) Create MRP with Following compounds and select the serial non-FIFO structure.  
![6 1](https://user-images.githubusercontent.com/77261450/172123058-a0b0e444-d21a-4ea4-a80f-33b34cede6f6.png)
As we see the above serial no have cost price is $50
3 Check the finish goods Cost.
 ![7](https://user-images.githubusercontent.com/77261450/172123405-6118b3c4-d3db-4b9d-93e1-10a25396f1a9.png)
4) Create Another MO with same Component Selected the different Serial check the Cost of Finish Goods
![8](https://user-images.githubusercontent.com/77261450/172123678-72d7ce23-0730-4790-aa91-d89d964a1180.png)
![9](https://user-images.githubusercontent.com/77261450/172123710-5507d31e-98fa-4ee2-a763-c5a44515f897.png)

**Comment by Chanakya-OSI** [comment]
@agyamuta this is for you to review.
